---
- hosts: localhost
  tasks:
    - name: "Install homebrew"
      include_role:
        name: geerlingguy.mac.homebrew

    - name: "Make sure homebrew bin is in path"
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: "/opt/homebrew/bin"
      become: true
      become_user: root

    - name: "Add custom homebrew repos"
      community.general.homebrew_tap:
        name: [
          "koekeishiya/formulae",
        ]

    - name: "Install packages via brew casks"
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - datagrip
        - pycharm
        - tableplus
        - google-chrome
        - iterm2
        - ngrok
        - slack
        - zoom
        - spotify
        - karabiner-elements
        - multitouch
        - hpedrorodrigues/tools/dockutil

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - fish
        - asdf
        - awscli
        - coreutils
        - curl
        - htop
        - openssl
        - postgresql
        - redis
        - sqlite3
        - tmux
        - unzip
        - vim
        - watchman
        - shellcheck
        - git
        - tig
        - yabai
        - skhd

    - name: "Upgrade homebrew packages"
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: "Clear dock"
      shell: |
        defaults write com.apple.dock autohide -bool true
        defaults write com.apple.dock autohide-delay -float 0
        defaults write com.apple.dock autohide-time-modifier -float 0.4
        dockutil --remove all --no-restart
        dockutil --add /Applications/Google\ Chrome.app --no-restart
        dockutil --add /Applications/iTerm.app --no-restart
        dockutil --add /Applications/PyCharm.app --no-restart
        dockutil --add /Applications/Spotify.app

    - name: "Finder settings"
      shell: |
        defaults write NSGlobalDomain "AppleShowAllExtensions" -bool "true"
        defaults write com.apple.finder "AppleShowAllFiles" -bool "true"
        defaults write com.apple.finder "ShowPathbar" -bool "true"
        killall Finder

    - name: "Spaces settings"
      shell: |
        defaults write com.apple.dock "mru-spaces" -bool "false"
        defaults write com.apple.Accessibility ReduceMotionEnabled -bool TRUE
        killall Dock

    - name: "Keyboard settings"
      shell: |
       defaults write -g ApplePressAndHoldEnabled -bool false
       defaults write NSGlobalDomain NSUserDictionaryReplacementItems -array
       defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool FALSE
       defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool FALSE
       defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool FALSE
       defaults write com.apple.Accessibility KeyRepeatDelay -float "0.2"
       defaults write com.apple.Accessibility KeyRepeatInterval -float "0.02"
      
    - name: "Get the path to fish"
      become: false
      local_action: command which fish
      register: fish_path

    - name: "Ensure homebrew fish is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: "{{ fish_path.stdout }}"
      become: true

    - name: "Set fish as the default shell"
      shell: chsh -s $(which fish) {{ lookup('env', 'USER') }}
      become: true

    - name: "Get the path to asdf"
      become: false
      local_action: command brew --prefix asdf
      register: asdf_path

    - name: "Set up asdf in fish"
      ansible.builtin.lineinfile:
        path: "/Users/{{ lookup('env', 'USER') }}/.config/fish/config.fish"
        state: present
        line: "source {{ asdf_path.stdout }}/libexec/asdf.fish"

    - name: "Install asdf plugins"
      shell: |
        source {{ asdf_path.stdout }}/libexec/asdf.sh
        asdf plugin-add {{ item }} || exit 0
      with_items:
        - nodejs
        - python

    - name: "Install python"
      shell: |
        source {{ asdf_path.stdout }}/libexec/asdf.sh
        asdf install python 3.10.0
        asdf global python 3.10.0
        pip3 install ansible
        asdf reshim python

    - name: "Install node"
      shell: |
        source {{ asdf_path.stdout }}/libexec/asdf.sh
        bash {{ asdf_path.stdout }}/plugins/nodejs/bin/import-release-team-keyring
        asdf install nodejs 16.4.2
        asdf global nodejs 16.4.2

    - name: "Start window management"
      shell: |
        brew services start yabai
        brew services start skhd

